### ISSUE TITLE
Rune Breaker 

### ISSUE THREAD

**Issue by Cigar1** [tanjeffreyz/auto-maple-resources#15]
Well , Sometime rune doesn't solve the issue which lead to death if im AFK , is there anyway to solve that rune breaker issue ?

**Comment by Tsukino-uwu** [comment]
It can only solve normal runes, not weird colors/disappearing runes or the spinning ones
you shouldn't leave it unattended/fully afk either way, in case of other players or gm white room

**Comment by Cigar1** [comment]
is there any discord server that you guys talking in ? 
i've done Kenesis , and i got easy command book to be used

**Comment by Cigar1** [comment]
Cigar💠#3736
