### ISSUE TITLE
Invalid keyboard input Adele

### ISSUE THREAD

**Issue by Nekololizu** [tanjeffreyz/auto-maple-resources#4]
Whats the intended way to write the keyboard inputs assuming all keys are supported like home,end,pgup etc?
page_up & pgdn ? just guessing from what shows up in the start/stop control or is there a list for them ?

Getting this error when its trying to use buffs
```
##################
#    ENABLED     #
##################
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
```

**Comment by tanjeffreyz** [comment]
Yeah, I think just going with whatever shows up in the keybinds list, so "pageup" should be "page up". I've just updated `vkeys.py` with this.
